name: CI/CD Spring Boot com SQL

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    env:
      SPRING_DATASOURCE_URL: ${{ secrets.DATABASE_URL }}
      SPRING_DATASOURCE_USERNAME: ${{ secrets.DB_USER }}
      SPRING_DATASOURCE_PASSWORD: ${{ secrets.DB_PASSWORD }}
      TOKEN_API: ${{ secrets.TOKEN_API }}

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build com Maven
        run: mvn clean package --no-transfer-progress

      - name: Rodar testes
        run: mvn test --no-transfer-progress